CREATE TABLE `list_of_imported_food_goods` (
	`RECEIPT_NO` VARCHAR(100) NULL DEFAULT NULL,
	`NOTICE_GOODS_NAME` VARCHAR(500) NULL DEFAULT NULL,
	`BSN_OFC_NAME` VARCHAR(500) NULL DEFAULT NULL,
	`GOODS_KOR_NAME` VARCHAR(500) NULL DEFAULT NULL,
	`GOODS_ENG_NAME` VARCHAR(500) NULL DEFAULT NULL,
	`ITEM_NAME` VARCHAR(500) NULL DEFAULT NULL,
	`NOTICE_DATE` VARCHAR(100) NULL DEFAULT NULL,
	`FLOW_TO_DATE` VARCHAR(100) NULL DEFAULT NULL,
	`MANUFAC_NAME` VARCHAR(500) NULL DEFAULT NULL,
	`MANUFAC_COUNTRY_NAME` VARCHAR(100) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
